repos:
  # ─────────────  PYTHON STYLE  ─────────────
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
    hooks:
      - id: mypy
        args: [--install-types, --non-interactive, --ignore-missing-imports]

  # ─────────────  DJANGO / HTML  ─────────────
  - repo: https://github.com/Riverside-Healthcare/djlint
    rev: v1.36.4
    hooks: [{ id: djlint, stages: [pre-commit] }]

  # ─────────────  YAML / JSON / MARKDOWN  ─────────────
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-yaml
      - id: pretty-format-json
