[tool.mypy]
python_version = "3.12"
strict = true
ignore_missing_imports = true

[tool.ruff]
line-length = 88 # Compatible with black
target-version = "py312" # Specify your Python version

# E: pycodestyle, F: pyflakes, I: isort, B: flake8-bugbear, UP: pyupgrade
select = ["E", "F", "I", "B", "UP"]
ignore = [
    "E501", # Ignore line length, as ruff format handles it
]
